### ISSUE TITLE
Regression:  XML checks fail if less than character < is inside a string value

### ISSUE THREAD

**Issue by mstovenour** [SIPp/sipp#721] opened 2024-04-20 18:23 UTC
I have existing scenario files that are modeled directly out of the documentation:
https://sipp.readthedocs.io/en/latest/scenarios/variables.html?highlight=search_in#variables

```
<recv request="INVITE">
  <action>
    <ereg regexp="<sip:([^;@]*)" search_in="hdr" header="To:" assign_to="dummy,uri" />
  </action>
</recv>
<Reference variables="dummy" />
```

The less than character `<` inside the quotes of the regexp tag (`regexp="<sip:([^;@]*)"`)  causes the following failure when running with any release after v3.6.0:
`2024-04-20      12:55:46.344095 1713635746.344095: Invalid XML in scenario`

Existing scenario files work fine up until v3.5.3.  They will not pass the XML check logic starting with v3.6.0.

I'm pretty sure this commit introduced the regression:
https://github.com/SIPp/sipp/commit/411ccf40ab8fe77293e4a0f3ac8ad7739569d293 @wdoekes

It might be the deletion of this function call as the xp_find_start_tag_end() function is checking for embedded strings in quotes "".
![image](https://github.com/SIPp/sipp/assets/2981982/6522003c-2d51-442f-9cc4-a4ba5e296f75)

**Comment by mstovenour** [comment] 2024-04-20 23:32
This looks like a duplicate of #670

**Comment by wdoekes** [comment] 2024-04-21 18:55
Which in turn looks like a duplicate of #414 

But if the documentation wrongly advises `="<..."` then that should be fixed.

**Comment by mstovenour** [comment] 2024-04-22 12:20
I see the conversation in #414 and I'll concede that SIPp previously supported _invalid_ XML syntax, but it did so for two decades; yes I'm old.  I think this would have taken me a lot less time if SIPp were to implement the following changes:
* Change documentation so it doesn't suggest incorrect language (pull request coming)
* Change error message so I clearly calls out the regression to give future me a hint (pull request coming)
* Add line number counting while parsing XML so this syntax check can explicitly state the line number (can you meet half way and help with this one?)

**Comment by mstovenour** [comment] 2024-04-22 16:28
I just submitted a pull request for my suggestion to yet more notes for future me.

**Closed** 2024-04-29 12:58 UTC
