### ISSUE TITLE
Cannot make 3.5.1 - no include/version.h file

### ISSUE THREAD

**Issue by agentgoblin** [SIPp/sipp#218] opened 2016-04-01 08:48 UTC
When I'm tried build 3.5.1 from source, I have error:

> make: *** No rule to make target `include/version.h', needed by `src/call.cpp'.  Stop.

What additional information you need?

**Comment by wdoekes** [comment] 2016-04-01 09:21
Sounds like a duplicate of #190 and you've downloaded the wrong file -- please reopen if there really is an issue.

**Closed by wdoekes** 2016-04-01 09:21 UTC

**Comment by agentgoblin** [comment] 2016-04-01 10:47
https://github.com/SIPp/sipp/releases/download/v3.5.1/sipp-3.5.1.tar.gz work well, thank you.

But what for other files?

**Comment by wdoekes** [comment] 2016-04-01 12:06
Please rephrase your question. I have no idea what you're asking.

**Comment by lemenkov** [comment] 2016-04-01 12:13
@wdoekes I suppose @agentgoblin asks for a previous versions. I can't remember if anyone noticed this issue before but if the issue does exists, one can simply fix it with _echo_ command:

`echo #define SIPP_VERSION \"v3.5.1\" > include/version.h`

Just execute this before build (don't forget to adjust version number).

**Comment by wdoekes** [comment] 2016-04-01 12:16
For the previous version, he should download https://github.com/SIPp/sipp/releases/download/v3.5.0/sipp-3.5.0.tar.gz and not the "github download the source without git stuff"-zip.

Or, for random versions, just checkout the git repo directly.

**Comment by agentgoblin** [comment] 2016-04-07 14:35
Thanks for answers. I asked about these files without "include/version.h":
https://github.com/SIPp/sipp/archive/v3.5.1.zip
https://github.com/SIPp/sipp/archive/v3.5.1.tar.gz
But nevermind, I read the **NOTE** on release download page now.
