### ISSUE TITLE
Add -ltinfo at the end of LIBS in Makefile

### ISSUE THREAD

**Issue by Harshad18** [SIPp/sipp#321] opened 2017-08-30 15:39 UTC
Hi,

While installing sipp-3.5.1 I got an link error -
Build fails with link error:
/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/ld: src/sipp-screen.o: undefined reference to symbol 'stdscr'

after searching on Google a bit I found out that - 
adding '-ltinfo' in Makefile at 'LIBS = -lpcap -lm -lpthread -lrt -ldl -lncurses' solves it
-> "LIBS = -lpcap -lm -lpthread -lrt -ldl -lncurses -ltinfo"

I think it will be a good addition. Installation process will become easier for those who will use it in the future.

Thanks,
Harshad.

**Comment by wdoekes** [comment] 2017-08-30 20:15
Dupe of #271.

Unfortunately I cannot just add stuff to the LIBS without autoconf stuff. It solves it for your machine, but it may break the build for others.

Thanks for the report though. Pull requests are appreciated!

**Closed by wdoekes** 2017-08-30 20:15 UTC

**Comment by Darkeye9** [comment] 2017-11-01 23:16
Currenty I think this is the case for anyone using Arch Linux.

https://bbs.archlinux.org/viewtopic.php?id=231224
