### ISSUE TITLE
SIPp does not bind to IP address given in "-i" option

### ISSUE THREAD

**Issue by vishwaspg** [SIPp/sipp#318] opened 2017-07-13 09:48 UTC
When i run a sipp tcp call, the server is getting the primary ip address and not the ip address given in the -i option. Because the INVITE, FROM and Via contains the IP address given in "-i", the calls are failing. 
This is happening for TCP calls and from version 3.5.1 onwards. I dont see this issue for 3.4.1
Please see the below commands run. Any input to resolve this?? Thanks in advance.

./sipp -sn uas -i 10.54.56.134 -p 6810 -m 1 -t t1
./sipp -sn uac -i 10.54.56.241 -p 6820 10.54.56.134:6810 -m 1 -t t1 -trace_err

This is the netcat output:

Connection from 10.54.56.4 port 6820 [tcp/*] accepted
INVITE sip:service@10.54.56.134:6810 SIP/2.0
Via: SIP/2.0/TCP 10.54.56.241:6820;branch=z9hG4bK-2202-1-0
From: sipp <sip:sipp@10.54.56.241:6820>;tag=2202SIPpTag001
To: service <sip:service@10.54.56.134:6810>
Call-ID: 1-2202@10.54.56.241
CSeq: 1 INVITE
Contact: sip:sipp@10.54.56.241:6820
Max-Forwards: 70
Subject: Performance Test
Content-Type: application/sdp
Content-Length:   129

So if you see it should pick 10.54.56.241 as the IP but instead picks the primary IP of the system 10.54.56.4

**Comment by wdoekes** [comment] 2018-04-20 15:33
Duplicate of #83, right?

**Closed by wdoekes** 2018-04-20 15:33 UTC
