### ISSUE TITLE
SIPp console shows retransmissions during load testing. What can I do to eliminate those ?

### ISSUE THREAD

**Issue by oza4h07** [SIPp/sipp#336] opened 2018-03-07 16:38 UTC
Hello,
I'm currently load testing an Asterisk box using SIPp on a VMWare instance.
SIPp comes from Debian Stretch  package (package sip-tester corresponding to SIPp 3.2).
Tests are done with UDP and I'm sending RTP media along SIP signals.
I'm seeing UDP restrans and I'm wondering if I can do something to decrease or eliminate those.

From experience, what do you suggest ?
Best regards

**Comment by wdoekes** [comment] 2018-04-20 15:04
Not a bug. If Asterisk is not responding, we should retransmit. If Asterisk is retransmitting, we should reply.

Not much to say there. If you think there is a problem in SIPp, you'll need to provide more info.

Closing.

**Closed by wdoekes** 2018-04-20 15:04 UTC
