### ISSUE TITLE
Terminal output is unreadable in MacOS (Catalina)

### ISSUE THREAD

**Issue by stemis** [SIPp/sipp#413] opened 2019-08-09 13:21 UTC
Hello,

I have Mac Version: `10.15 (19A512f)`
SIPp version: `SIPp v3.6.0-PCAP-RTPSTREAM`

When I run `sipp -sn uac <IP>`, the data printed to the terminal is not handled correctly and it is constantly printing new lines, making the output completely unreadable.

Please see an example screenshot below

![Sipp](https://user-images.githubusercontent.com/4124979/62781885-3d335080-bab9-11e9-8788-10eea18970c9.png)

The screen constantly jumps making it impossible to read anything

**Comment by wdoekes** [comment] 2019-08-26 07:19
@stemis: I'm sorry, I've already tried to fix problems in this area once before (see #76 and #102). But as I have no OSX, I don't have any means to reproduce.

**Comment by rkday** [comment] 2019-10-27 20:59
@stemis - `NCURSES_NO_SETBUF=1 ./sipp -sn uas` seems to stabilise it a bit for me on my Mac. I still see the symptoms from https://github.com/SIPp/sipp/pull/102#issuecomment-57734282, ocasional "rolling", but it's a lot more usable.

**Comment by rkday** [comment] 2019-10-29 21:48
I have the beginnings of what seems to be a fix in https://github.com/SIPp/sipp/pull/431.

**Comment by rkday** [comment] 2019-11-05 23:47
@stemis - if you can pull and build the latest code from https://github.com/SIPp/sipp/pull/431 and see if that works for you, that would be useful. It works on my Mac, but more testing is always good!

**Comment by rkday** [comment] 2019-11-10 16:17
Fixed by #431 .

**Closed by rkday** 2019-11-10 16:17 UTC
Labels: bug, request-feedback
