### ISSUE TITLE
Missing libz requirement

### ISSUE THREAD

**Issue by Whissi** [SIPp/sipp#143] opened 2015-05-27 20:58 UTC
When building sipp with `--with-rtpstream` *sipp* will link against *libz.so* but we don't check for libz in *configure* yet:

```
# ldd /var/tmp/portage/net-misc/sipp-9999/image/usr/bin/sipp
        linux-vdso.so.1 (0x00007fffa49de000)
        libcrypto.so.1.0.0 => /usr/lib64/libcrypto.so.1.0.0 (0x00007f53a31d0000)
        libssl.so.1.0.0 => /usr/lib64/libssl.so.1.0.0 (0x00007f53a2f5a000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f53a2d3f000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f53a2b3b000)
        libncurses.so.5 => /lib64/libncurses.so.5 (0x00007f53a28e4000)
        libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.2/libstdc++.so.6 (0x00007f53a25d4000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f53a22d8000)
        libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.2/libgcc_s.so.1 (0x00007f53a20c1000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f53a1d1e000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f53a1b08000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f53a360e000)
```

I checked git master (aka commit dfe82657dd).

**Comment by wdoekes** [comment] 2015-05-28 06:47
Thanks for the report! If you also have a patch, that'd be great.

**Comment by wdoekes** [comment] 2015-06-20 12:58
Okay. Cannot reproduce with today's master (0909a0a7c).

```
$ ./sipp -v | grep SIPp
 SIPp v3.5.0-rc1-RTPSTREAM built Jun 20 2015, 14:54:09.
$ ldd ./sipp | grep z
$ ldd ./sipp_unittest | grep z
```

Can you?

**Comment by wdoekes** [comment] 2015-06-20 13:03
Cannot reproduce with dfe8265 either.

```
$ git checkout dfe82657d
$ make clean
$ ./configure --with-rtpstream  >/dev/null 2>&1
$ make -j5 >/dev/null 2>&1
$ echo $?
0
$ ldd ./sipp | grep z
```

Closing this out. Please reopen if you can supply more information.

**Closed by wdoekes** 2015-06-20 13:03 UTC

**Comment by Whissi** [comment] 2015-06-20 13:47
I am still able to reproduce it with dfe8265, but with openssl:
```
./configure \
	[...]
	--with-openssl \
	--without-pcap \
	--without-rtpstream \
	--without-sctp \
	--without-gsl
```
See
```
ldd /var/tmp/portage/net-misc/sipp-9999/image/usr/bin/sipp
        linux-vdso.so.1 (0x00007ffe7dd52000)
        libcrypto.so.1.0.0 => /usr/lib64/libcrypto.so.1.0.0 (0x00007fcd122ec000)
        libssl.so.1.0.0 => /usr/lib64/libssl.so.1.0.0 (0x00007fcd12076000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fcd11e5b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fcd11c57000)
        libncurses.so.5 => /lib64/libncurses.so.5 (0x00007fcd11a00000)
        libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.2/libstdc++.so.6 (0x00007fcd116f0000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fcd113f4000)
        libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.2/libgcc_s.so.1 (0x00007fcd111dd000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fcd10e3a000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fcd10c24000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fcd1272b000)
```

I guess you are unable to reproduce because your openssl was build without zlib (`--no-zlib`). Looks like *sipp* is picking up on libz because OpenSSL's pkgconfig file contains "-lz".

**Comment by Whissi** [comment] 2015-06-20 14:07
Never mind. My mistake:

*libcrypto.pc* contains "-lz" when OpenSSL was build with *zlib* support, but it is listed in *Libs.private*.
So using *ldd* was wrong because it is listing every dependency. Using *lddtree* would have been better, because this will show you that *libz.so.1* is not a dependency of *sipp* but of *libcrypto.so.1* which is used by *sipp*.

Sorry for wasting your time.

**Comment by wdoekes** [comment] 2015-06-20 14:24
No worries. Good that you figured it out :)
